spring.application.name=api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:dbsaktiform}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Postgre1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1700000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=300000

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=60000

spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

whatsapp.api.username=${WHATSAPP_API_USERNAME:admin}
whatsapp.api.password=${WHATSAPP_API_PASSWORD:admin}
whatsapp.multidevice.api.url=${WHATSAPP_MULTIDEVICE_API_URL:http://103.49.239.5:3000}

minio.url=${MINIO_URL:http://103.49.239.5:9500}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:saktiform-media}
minio.bucket.produk=${MINIO_BUCKET_PRODUK:produk-media}
minio.prefix=${MINIO_PREFIX:media}
minio.public-url=${MINIO_PUBLIC_URL:http://103.49.239.5:9500}

saktiform.api.checkout.url=${SAKTIFORM_CHECKOUT_URL:http://103.49.239.5:3500}

app.superadmin.username=${SUPERADMIN_USERNAME:superadmin}
app.superadmin.password=${SUPERADMIN_PASSWORD:PasswordAdmin1234}

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

server.forward-headers-strategy=framework

springdoc.swagger-ui.enabled=true

server.port=8081

