spring.application.name=api


# PostgreSQL JDBC URL
spring.datasource.url=jdbc:postgresql://${DB_HOST:103.49.239.5}:${DB_PORT:5432}/${DB_NAME:dbsaktiform}
spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.idle-timeout=300000

# Disable Hibernate SQL logging
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false


# Username dan Password PostgreSQL
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:Password1234}

# Driver JDBC PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.web.resources.static-locations=classpath:/static/,file:./uploads/



whatsapp.api.username=${WHATSAPP_API_USERNAME:admin}
whatsapp.api.password=${WHATSAPP_API_PASSWORD:admin}
whatsapp.api.url=${WHATSAPP_API_URL:http://[::1]}
whatsapp.multidevice.api.url=${WHATSAPP_MULTIDEVICE_API_URL_IMAGE:http://103.49.239.5:3000}

saktiform.api.url=${SAKTIFORM_API_URL:http://103.49.239.5:8080}
saktiform.api.checkout.url=${SAKTIFORM_CHECKOUT_URL:http://localhost:3000}
media.base.directory=${MEDIA_BASE_DIRECTORY:/opt/saktiform-data/media}

app.superadmin.username=${SUPERADMIN_USERNAME:superadmin}
app.superadmin.password=${SUPERADMIN_PASSWORD:PasswordAdmin1234}

logging.level.com.saktiform.api.service.chat=DEBUG

openai.api.key=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
gemini.api.key=AIzaSyCFW2fzqSm_1nt_L742VAJLH53zSmOmHAY